### PR TITLE
add frame fragmentation support (continuation)

### PR DESCRIPTION
**Pull request by AlexanderShirokih**
Apache Tomcat server cuts responce into frames with size up to 8192 bytes. So i can't receive responce in a single frame and i wrote some piece of code to be able receive multiple frames in one message.

### CODE REVIEW

**Comment by AlexanderShirokih** [comment]
I have bug in first commit, when bis.read(byte[]) reads array not fully. So i bring you version with for loop. Now it seems to work fine.

**Comment by vdbemden** [comment]
I used the frame fragmentation support in my own code. This worked very well and saved me from developping it on my own. Please consider commiting it to your repository !

**Comment by romichandra** [comment]
guys any updates on this PR?

**Comment by gusavila92** [comment]
Hey folks thanks for looking into this. That fragment support was one of main things I wanted to do when I developed this library, but due to the lack of time I wasn't able to do it. I'm reactivating my work on this library so I will set up an Apache Tomcat server to test it as soon as possible with many test cases. Cheers!

**Pull request merged**
